### ISSUE TITLE
Unexpected permission error while building package

### ISSUE THREAD

**Issue by giorgiosironi** [nubs/docker-php-minimal#5]
I was receiving this error:
```
[14:11:18][giorgio@Newton:~/code/docker-php-minimal]$ sudo docker run --interactive --tty --rm --volume "$(pwd)/php-7.1.0-alpha.1/php:/package" nubs/arch-build           
==> ERROR: You do not have write permission to create packages in /package.
    Aborting...
```
I had to do:
```
[14:15:37][giorgio@Newton:~/code/docker-php-minimal]$ chmod 777 php-7.1.0-alpha.1/php                                                                                     
```
to be able to build the package.

May be related to: https://github.com/docker/docker/issues/783

If this is expected, it can be added to the `README`?

**Comment by nubs** [comment]
Yeah, the README could definitely use some improvements.  I'll try to write something up.

The issue is that the builds shouldn't be done as root, so part of nubs/arch-build is to create a build user (uid `1000`) to execute the build as.  With docker volume mounts, the owner of the volume on the host is the same as the owner of that directory within the container, so if your directory on your host is owned by a uid/gid different than `1000`, then you need to do something to give the build user access.  For example, you could run `chgrp 1000 php-7.1.0-alpha.1/php` and be set.
