### ISSUE TITLE
Still kinda large

### ISSUE THREAD

**Issue by mozzymoz** [nubs/docker-php-minimal#6]
Hi there, I just tested out your implementation, however I found that the archlinux image itself is already 100MB large. A while ago I experimented in building php in a containter to a volume and then extract all the files needed to run PHP from there into an own image. That actually worked but the building process was kind of tedious.

I used https://github.com/larsks/dockerize to extract the dependencies and used some bash-ldd magic to even get the runtime dependencies of php extensions. Sadly I lost the bash script which does all that magic, but I will try to write up something to recreate it.

The archilinux php image you are building could be used as a source for that.

The resulting image I had were only 80MB (nginx + php-fpm included).

**Comment by mozzymoz** [comment]
I just checked the alpine images from the official php images. the 7.0.11 is less than 70MB ;)

**Comment by nubs** [comment]
You're definitely right that these images could be quite a bit smaller.  The word "minimal" in the name of the repo is misleading as well and should probably be changed to something more descriptive of what I'm actually doing here.  The main reason I decided to use archlinux was for ease of development and maintenance since I am maintaining hundreds of these docker images.

**Comment by mozzymoz** [comment]
If you are interested, I rebuilt my script to make minimal docker images. I tested it with nginx, php and php-fpm https://github.com/mozzymoz/packager
